# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: PowerShell
    type: github
    endpoint: mysvcconnection
    name: santosh-gh/cheat-sheet
    ref: cheat-sheet/PowerShell



steps:
- checkout: PowerShell
- script: echo Hello, world!
  displayName: 'Run a one-line script 1'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
# - task: AzurePowerShell@5
#   inputs:
#     azureSubscription: my-arm-service-connection
#     scriptType: filePath
#     scriptPath: $(Build.SourcesDirectory)\PowerShell\virtual-network\virtual-network-multi-tier-application\virtual-network-multi-tier-application.ps1
#     scriptArguments:
#       -Arg1 val1 `
#       -Arg2 val2 `
#       -Arg3 val3
#     azurePowerShellVersion: latestVersion
#     pwsh: true
